package com.raunak.daytimeline

import androidx.compose.foundation.background
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowRight
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.raunak.daytimeline.domain.TaskModel
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import kotlin.math.roundToInt

private val Ink=Color(0xFF17222A); private val Cream=Color(0xFFF7F5F0); private val Card=Color(0xFFFFFEFC); private val Sage=Color(0xFF4E7965); private val Muted=Color(0xFF77818A)

@Composable fun PremiumHome(){
 val app=remember{AppContainer(androidx.compose.ui.platform.LocalContext.current.applicationContext)}; val vm:PlannerViewModel=viewModel(factory=PlannerViewModel.Factory(app)); val tasks by vm.tasks.collectAsStateWithLifecycle(); val date by vm.currentDate.collectAsStateWithLifecycle(); val pomo by vm.pomodoro.collectAsStateWithLifecycle(); var tab by remember{mutableIntStateOf(0)}; var add by remember{mutableStateOf(false)}; var selected by remember{mutableStateOf<TaskModel?>(null)}
 MaterialTheme(colorScheme=lightColorScheme(background= Cream,surface=Card,primary=Sage,onSurface=Ink)){ Scaffold(containerColor=Cream,bottomBar={NavigationBar(containerColor=Card){listOf(Icons.Default.CalendarToday to "Today",Icons.Default.Timer to "Focus",Icons.Default.Insights to "Insights",Icons.Default.Tune to "Settings").forEachIndexed{i,p->NavigationBarItem(tab==i,{tab=i},{Icon(p.first,null)},{Text(p.second)})}}},floatingActionButton={if(tab==0)FloatingActionButton({add=true},containerColor=Ink,contentColor=Color.White){Icon(Icons.Default.Add,null)}}){pad->Box(Modifier.fillMaxSize().padding(pad)){when(tab){0->Timeline(tasks,date,vm){selected=it};1->Focus(pomo,tasks,vm);2->Insights(tasks);3->Settings(vm)}}}}
 }
 if(add)AddSheet(vm){add=false}; selected?.let{TaskSheet(it,vm){selected=null}}
}

@Composable private fun Timeline(tasks:List<TaskModel>,date:LocalDate,vm:PlannerViewModel,onTask:(TaskModel)->Unit){val total=tasks.sumOf{(it.endMinute-it.startMinute).coerceAtLeast(0)};val done=tasks.filter{it.completed}.sumOf{(it.endMinute-it.startMinute).coerceAtLeast(0)};val pct=if(total==0)0 else done*100/total;LazyColumn(contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(13.dp)){item{Row(Modifier.fillMaxWidth(),Arrangement.SpaceBetween,Alignment.CenterVertically){Column{Text(if(date==LocalDate.now())"Good day." else "Your plan",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text(date.format(DateTimeFormatter.ofPattern("EEEE, d MMMM")),color=Muted)}Box(Modifier.size(46.dp).clip(CircleShape).background(Ink),Alignment.Center){Text("$pct%",color=Color.White,fontWeight=FontWeight.Bold)}}};item{Surface(RoundedCornerShape(28.dp),modifier=Modifier.fillMaxWidth()){Box(Modifier.background(Brush.linearGradient(listOf(Ink,Color(0xFF315046)))).padding(20.dp)){Column(verticalArrangement=Arrangement.spacedBy(9.dp)){Text("TODAY",color=Color(0xFFB9CCC2),style=MaterialTheme.typography.labelMedium);Text("${tasks.count{!it.completed}} things left",color=Color.White,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.SemiBold);Text("${total/60}h ${total%60}m planned  ·  ${done/60}h ${done%60}m done",color=Color(0xFFC9D3D1));LinearProgressIndicator({pct/100f},Modifier.fillMaxWidth().height(7.dp).clip(CircleShape),Color(0xFFA8C7B7),Color.White.copy(.12f))}}}};item{DateStrip(date,vm)};item{Text("Timeline",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};if(tasks.isEmpty())item{Surface(RoundedCornerShape(24.dp),color=Card){Column(Modifier.fillMaxWidth().padding(28.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.Spa,null,tint=Sage,Modifier.size(42.dp));Text("A quiet day",fontWeight=FontWeight.SemiBold);Text("Add something when you are ready.",color=Muted)}}}else items(tasks.sortedBy{it.startMinute},key={it.id}){t->TaskCard(t,{onTask(t)},{vm.toggleComplete(t,!t.completed)})};item{Spacer(Modifier.height(70.dp))}}}

@Composable private fun DateStrip(date:LocalDate,vm:PlannerViewModel){Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){(-3..3).forEach{i->val d=date.plusDays(i.toLong());val sel=i==0;Surface(RoundedCornerShape(18.dp),color=if(sel)Ink else Card,onClick={if(i<0)vm.onPrevDay();if(i>0)vm.onNextDay()}){Column(Modifier.padding(horizontal=14.dp,vertical=10.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(d.format(DateTimeFormatter.ofPattern("EEE")),color=if(sel)Color.White else Muted);Text("${d.dayOfMonth}",color=if(sel)Color.White else Ink,fontWeight=FontWeight.Bold)}}}}}

@Composable private fun TaskCard(t:TaskModel,onClick:()->Unit,onComplete:()->Unit){Surface(onClick=onClick,shape=RoundedCornerShape(22.dp),color=Card,shadowElevation=1.dp,modifier=Modifier.fillMaxWidth()){Row(Modifier.padding(14.dp),Alignment.CenterVertically){Box(Modifier.width(5.dp).height(64.dp).clip(CircleShape).background(Color(t.colorHex)));Column(Modifier.weight(1f).padding(start=13.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Text(t.title,fontWeight=FontWeight.SemiBold,maxLines=1,overflow=TextOverflow.Ellipsis);Text("${tm(t.startMinute)} — ${tm(t.endMinute)}  ·  ${t.endMinute-t.startMinute} min",color=Muted,style=MaterialTheme.typography.bodySmall);Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){if(t.pomodoroEnabled)Chip("Pomodoro",Icons.Default.Timer);if(t.recurrenceType!="NONE")Chip("Repeats",Icons.Default.Repeat);if(t.notes.isNotBlank())Chip("Notes",Icons.Default.Notes)}};Checkbox(t.completed){onComplete()}}}}
@Composable private fun Chip(s:String,icon:androidx.compose.ui.graphics.vector.ImageVector){Surface(RoundedCornerShape(50),color=Color(0xFFEAF0EC)){Row(Modifier.padding(horizontal=7.dp,vertical=4.dp),Alignment.CenterVertically){Icon(icon,null,tint=Sage,Modifier.size(13.dp));Spacer(Modifier.width(4.dp));Text(s,color=Sage,style=MaterialTheme.typography.labelSmall)}}}

@Composable private fun Focus(p:com.raunak.daytimeline.data.PomodoroStateEntity,tasks:List<TaskModel>,vm:PlannerViewModel){Column(Modifier.fillMaxSize().padding(22.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("FOCUS",color=Sage,fontWeight=FontWeight.Bold);Spacer(Modifier.height(22.dp));Surface(CircleShape,color=Ink,modifier=Modifier.size(245.dp)){Box(Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Text("%02d:%02d".format(p.remainingSeconds/60,p.remainingSeconds%60),color=Color.White,style=MaterialTheme.typography.displayMedium,fontWeight=FontWeight.Light);Text(p.phase,color=Color(0xFFB8C8C0))}}};Spacer(Modifier.height(22.dp));Text("One thing at a time.",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.SemiBold);Text("Focus without leaving the timeline.",color=Muted);Spacer(Modifier.height(20.dp));Row(horizontalArrangement=Arrangement.spacedBy(10.dp)){Button({if(p.running)vm.pausePomodoro()else vm.resumePomodoro()}){Icon(if(p.running)Icons.Default.Pause else Icons.Default.PlayArrow,null);Spacer(Modifier.width(6.dp));Text(if(p.running)"Pause" else "Resume")};OutlinedButton(vm::resetPomodoro){Text("Reset")}};Spacer(Modifier.height(15.dp));tasks.take(4).forEach{t->ListItem({Text(t.title)},{Text("${tm(t.startMinute)} · ${t.endMinute-t.startMinute} min",color=Muted)}, {Icon(Icons.Default.RadioButtonUnchecked,null)},{IconButton({vm.startPomodoro(t.id)}){Icon(Icons.Default.PlayArrow,null)}})}}

@Composable private fun Insights(tasks:List<TaskModel>){val total=tasks.size;val done=tasks.count{it.completed};val focus=tasks.count{it.pomodoroEnabled};LazyColumn(contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Insights",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text("Your day, without noise.",color=Muted)};item{Stat("Completion","$done / $total",if(total==0)0f else done.toFloat()/total,Icons.Default.CheckCircle)};item{Stat("Focus blocks","$focus",if(total==0)0f else focus.toFloat()/total,Icons.Default.Timer)};item{Stat("Planned time","${tasks.sumOf{it.endMinute-it.startMinute}/60}h ${tasks.sumOf{it.endMinute-it.startMinute}%60}m",1f,Icons.Default.Schedule)};item{Text("Categories",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};tasks.groupBy{it.category.ifBlank{"Other"}}.forEach{(c,l)->ListItem({Text(c)},{Text("${l.size} blocks · ${l.sumOf{it.endMinute-it.startMinute}} min",color=Muted)},{Box(Modifier.size(12.dp).clip(CircleShape).background(Color(l.first().colorHex)))})}}}
@Composable private fun Stat(t:String,v:String,p:Float,icon:androidx.compose.ui.graphics.vector.ImageVector){Surface(RoundedCornerShape(24.dp),color=Card){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){Row(Modifier.fillMaxWidth(),Arrangement.SpaceBetween){Text(t,color=Muted);Icon(icon,null,tint=Sage)};Text(v,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);LinearProgressIndicator({p.coerceIn(0f,1f)},Modifier.fillMaxWidth().height(7.dp).clip(CircleShape),Sage,Color(0xFFE7E5DF))}}}

@Composable private fun Settings(vm:PlannerViewModel){val s by vm.settings.collectAsStateWithLifecycle();LazyColumn(contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Settings",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text("Quiet controls for your day.",color=Muted)};item{Toggle("Auto-scroll to now","Open today at the current time",s.autoScrollNow){vm.updateSettings{copy(autoScrollNow=it)}}};item{Toggle("Show completed","Keep finished blocks visible",s.showCompleted){vm.updateSettings{copy(showCompleted=it)}}};item{Setting("Day starts",tm(s.dayStartMinute),Icons.Default.WbSunny)};item{Setting("Day ends",tm(s.dayEndMinute),Icons.Default.NightsStay)};item{Setting("Storage","On-device · offline",Icons.Default.Lock)};item{Surface(RoundedCornerShape(22.dp),color=Color(0xFFE9F0EA)){Row(Modifier.padding(16.dp),Alignment.CenterVertically){Icon(Icons.Default.WifiOff,null,tint=Sage);Spacer(Modifier.width(12.dp));Column{Text("Private by default",fontWeight=FontWeight.SemiBold);Text("No server is required for your core day.",color=Color(0xFF5C6B63))}}}}}}
@Composable private fun Toggle(t:String,sub:String,c:Boolean,f:(Boolean)->Unit){Surface(RoundedCornerShape(22.dp),color=Card){Row(Modifier.fillMaxWidth().padding(16.dp),Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(t,fontWeight=FontWeight.SemiBold);Text(sub,color=Muted,style=MaterialTheme.typography.bodySmall)};Switch(c,f)}}}
@Composable private fun Setting(t:String,v:String,icon:androidx.compose.ui.graphics.vector.ImageVector){Surface(RoundedCornerShape(22.dp),color=Card){ListItem({Text(t)},{Text(v,color=Muted)},{Icon(icon,null,tint=Sage)},{Icon(Icons.AutoMirrored.Filled.KeyboardArrowRight,null,tint=Muted)})}}

@OptIn(ExperimentalMaterial3Api::class) @Composable private fun AddSheet(vm:PlannerViewModel,close:()->Unit){var title by remember{mutableStateOf("")};var st by remember{mutableStateOf("09:00")};var en by remember{mutableStateOf("10:00")};var notes by remember{mutableStateOf("")};var pomo by remember{mutableStateOf(true)};ModalBottomSheet({close()}){Column(Modifier.padding(20.dp).fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(11.dp)){Text("New block",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);OutlinedTextField(title,{title=it},label={Text("What are you doing?")},modifier=Modifier.fillMaxWidth());Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(st,{st=it},label={Text("Start")},modifier=Modifier.weight(1f));OutlinedTextField(en,{en=it},label={Text("End")},modifier=Modifier.weight(1f))};Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf(15,30,45,60,90,120).forEach{m->AssistChip({en=tm(pm(st)+m)},{Text(if(m<60)"${m}m" else "${m/60}h")})}};OutlinedTextField(notes,{notes=it},label={Text("Notes")},modifier=Modifier.fillMaxWidth(),minLines=2);Row(Modifier.fillMaxWidth(),Arrangement.SpaceBetween,Alignment.CenterVertically){Text("Pomodoro");Switch(pomo,{pomo=it})};Button({if(title.isNotBlank()){val a=pm(st);vm.addOrUpdateTask(null,title.trim(),a,pm(en).coerceAtLeast(a+5),pomo,notes,1,"NONE","NONE",10);close()}},Modifier.fillMaxWidth()){Icon(Icons.Default.Add,null);Spacer(Modifier.width(7.dp));Text("Add to my day")};Spacer(Modifier.height(18.dp))}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun TaskSheet(t:TaskModel,vm:PlannerViewModel,close:()->Unit){ModalBottomSheet({close()}){Column(Modifier.padding(22.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text(t.title,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("${tm(t.startMinute)} — ${tm(t.endMinute)}",color=Muted);if(t.notes.isNotBlank())Text(t.notes);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilledTonalButton({vm.toggleComplete(t,!t.completed);close()}){Text(if(t.completed)"Reopen" else "Complete")};OutlinedButton({vm.duplicateTask(t);close()}){Text("Duplicate")};OutlinedButton({vm.deleteTask(t);close()}){Text("Delete")}};if(t.pomodoroEnabled)Button({vm.startPomodoro(t.id);close()},Modifier.fillMaxWidth()){Icon(Icons.Default.Timer,null);Spacer(Modifier.width(7.dp));Text("Start focus")}}}}
private fun tm(m:Int)="%02d:%02d".format((m/60).coerceIn(0,23),m%60);private fun pm(s:String):Int{val p=s.trim().split(":");return((p.getOrNull(0)?.toIntOrNull()?:0)*60+(p.getOrNull(1)?.toIntOrNull()?:0)).coerceIn(0,1439)}
